language: java
jdk:
- openjdk8

branches:
  only: # 오직 master브랜치에 push될때만 수행됩니다.
  - master

# Travis CI 서버의 Home
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

# master 브랜치에 PUSH 되었을때 수행하는 명령어입니다
# 여기선 프로젝트 내부에 둔 gradlew을 통해 clean & build 를 수행합니다.
script: "./gradlew clean build"

before_deploy:
- zip -r Squirrel *
- mkdir -p deploy
- mv Squirrel.zip deploy/Squirrel.zip

deploy:
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
  bucket: squirrel-deploy # S3 버킷
  key: Squirrel.zip # 빌드 파일을 압축해서 전달
  bundle_type: zip
  application: squirrel-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
  deployment_group: squirrel-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    repo: jhleed/Squirrel #Github 주소
    branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email: # Email외에도 Slack이 있으니, 관심있으신 분들은 링크1, 링크2를 참고하여 Slack도 추가하시는걸 추천드립니다.
    recipients:
    - jhleed3@gmail.com